/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package buccialexleonardogorettigestoregite;

import javax.swing.JOptionPane;

/**
 *
 * @author goretti.leonardo
 */
public class FRMCreazioneGita extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FRMCreazioneGita.class.getName());

    /**
     * Creates new form FRMCreazioneGita
     */
    public FRMCreazioneGita() {
        initComponents();
        
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        PNLCreazioneGita = new javax.swing.JPanel();
        LBLIdentificativoGita = new javax.swing.JLabel();
        LBLDurataGita = new javax.swing.JLabel();
        LBLLocationGita = new javax.swing.JLabel();
        TXTCodiceGita = new javax.swing.JTextField();
        TXTDurataGita = new javax.swing.JTextField();
        TXTLuogoGita = new javax.swing.JTextField();
        BTNCreaGita = new javax.swing.JButton();
        BTNCancellaGita = new javax.swing.JButton();
        BTNFormStudenti = new javax.swing.JButton();
        LBLTitoloGita = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TBLGite = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Creazione gita");
        getContentPane().setLayout(new java.awt.GridBagLayout());

        PNLCreazioneGita.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        LBLIdentificativoGita.setText("Codice gita:");

        LBLDurataGita.setText("Durata gita");

        LBLLocationGita.setText("Luogo gita:");

        BTNCreaGita.setText("Crea gita");
        BTNCreaGita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNCreaGitaActionPerformed(evt);
            }
        });

        BTNCancellaGita.setText("Cancella gita");

        BTNFormStudenti.setText("Passa alla gestione Studenti");

        LBLTitoloGita.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        LBLTitoloGita.setText("Creazione Gita");

        TBLGite.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Codice gita", "Durata gita", "Luogo gita"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TBLGite.setEnabled(false);
        jScrollPane1.setViewportView(TBLGite);

        javax.swing.GroupLayout PNLCreazioneGitaLayout = new javax.swing.GroupLayout(PNLCreazioneGita);
        PNLCreazioneGita.setLayout(PNLCreazioneGitaLayout);
        PNLCreazioneGitaLayout.setHorizontalGroup(
            PNLCreazioneGitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PNLCreazioneGitaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PNLCreazioneGitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BTNCreaGita, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BTNCancellaGita, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BTNFormStudenti, javax.swing.GroupLayout.DEFAULT_SIZE, 366, Short.MAX_VALUE)
                    .addGroup(PNLCreazioneGitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(LBLTitoloGita, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 247, Short.MAX_VALUE)
                        .addGroup(PNLCreazioneGitaLayout.createSequentialGroup()
                            .addGroup(PNLCreazioneGitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(LBLIdentificativoGita, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE)
                                .addComponent(LBLDurataGita, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(LBLLocationGita, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(PNLCreazioneGitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(TXTCodiceGita)
                                .addComponent(TXTDurataGita)
                                .addComponent(TXTLuogoGita, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)))))
                .addGap(42, 42, 42)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 456, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
        );
        PNLCreazioneGitaLayout.setVerticalGroup(
            PNLCreazioneGitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PNLCreazioneGitaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(PNLCreazioneGitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(PNLCreazioneGitaLayout.createSequentialGroup()
                        .addComponent(LBLTitoloGita)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(PNLCreazioneGitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LBLIdentificativoGita)
                            .addComponent(TXTCodiceGita, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(PNLCreazioneGitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LBLDurataGita)
                            .addComponent(TXTDurataGita, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(PNLCreazioneGitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LBLLocationGita)
                            .addComponent(TXTLuogoGita, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(BTNCreaGita)
                        .addGap(18, 18, 18)
                        .addComponent(BTNCancellaGita)
                        .addGap(18, 18, 18)
                        .addComponent(BTNFormStudenti)))
                .addContainerGap())
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 119;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 6, 6);
        getContentPane().add(PNLCreazioneGita, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BTNCreaGitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNCreaGitaActionPerformed
        try{
            Gita g = new Gita(TXTLuogoGita.getText(), TXTCodiceGita.getText(), Integer.parseInt(TXTDurataGita.getText()));
            
        }
        catch(java.lang.NumberFormatException e){
            JOptionPane.showMessageDialog(this, "Inserisci un numero per la durata");
        }
        catch(IllegalArgumentException e){
            JOptionPane.showMessageDialog(this, "Riempi tutti i campi");
        }
            
            
        
        
    }//GEN-LAST:event_BTNCreaGitaActionPerformed


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FRMCreazioneGita().setVisible(true));
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTNCancellaGita;
    private javax.swing.JButton BTNCreaGita;
    private javax.swing.JButton BTNFormStudenti;
    private javax.swing.JLabel LBLDurataGita;
    private javax.swing.JLabel LBLIdentificativoGita;
    private javax.swing.JLabel LBLLocationGita;
    private javax.swing.JLabel LBLTitoloGita;
    private javax.swing.JPanel PNLCreazioneGita;
    private javax.swing.JTable TBLGite;
    private javax.swing.JTextField TXTCodiceGita;
    private javax.swing.JTextField TXTDurataGita;
    private javax.swing.JTextField TXTLuogoGita;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
