/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package buccialexleonardogorettigestoregite;

/**
 *
 * @author goretti.leonardo
 */
public class FRMStudenti extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FRMStudenti.class.getName());

    /**
     * Creates new form FRMStudenti
     */
    public FRMStudenti() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PNLIscrizioneStudente = new javax.swing.JPanel();
        LBLTitoloStudenti = new javax.swing.JLabel();
        LBLNomeStudente = new javax.swing.JLabel();
        LBLCognomeStudente = new javax.swing.JLabel();
        LBLCodiceStudente = new javax.swing.JLabel();
        LBLSelezionaGita = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        LSTListaGite = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        TBLStudenti = new javax.swing.JTable();
        TXTNomeStudente = new javax.swing.JTextField();
        TXTCognomeStudente = new javax.swing.JTextField();
        TXTCodiceStudente = new javax.swing.JTextField();
        BTNCreaStudente = new javax.swing.JButton();
        BTNCancellaStudente = new javax.swing.JButton();
        BTNTornaIndietro = new javax.swing.JButton();
        BTNOrdinaGita = new javax.swing.JButton();
        LBLClasse = new javax.swing.JLabel();
        TXTClasse = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Iscrizione Studente");
        getContentPane().setLayout(new java.awt.GridBagLayout());

        PNLIscrizioneStudente.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        LBLTitoloStudenti.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
        LBLTitoloStudenti.setText("Iscrizione studente");

        LBLNomeStudente.setText("Nome studente:");

        LBLCognomeStudente.setText("Cognome studente:");

        LBLCodiceStudente.setText("ID studente:");

        LBLSelezionaGita.setText("Seleziona gita:");

        jScrollPane1.setViewportView(LSTListaGite);

        TBLStudenti.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nome", "Cognome", "ID", "Gita selezionata"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TBLStudenti.setEnabled(false);
        jScrollPane2.setViewportView(TBLStudenti);

        BTNCreaStudente.setText("Aggiungi studente");

        BTNCancellaStudente.setText("Cancella studente");

        BTNTornaIndietro.setText("Torna form gite");

        BTNOrdinaGita.setText("Ordina per gita");

        LBLClasse.setText("Classe:");

        javax.swing.GroupLayout PNLIscrizioneStudenteLayout = new javax.swing.GroupLayout(PNLIscrizioneStudente);
        PNLIscrizioneStudente.setLayout(PNLIscrizioneStudenteLayout);
        PNLIscrizioneStudenteLayout.setHorizontalGroup(
            PNLIscrizioneStudenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PNLIscrizioneStudenteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PNLIscrizioneStudenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(LBLTitoloStudenti, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(PNLIscrizioneStudenteLayout.createSequentialGroup()
                        .addGroup(PNLIscrizioneStudenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(LBLSelezionaGita, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(LBLCodiceStudente, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(LBLCognomeStudente, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
                            .addComponent(LBLNomeStudente, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(PNLIscrizioneStudenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TXTNomeStudente)
                            .addComponent(TXTCognomeStudente)
                            .addComponent(TXTCodiceStudente)))
                    .addComponent(jScrollPane1)
                    .addGroup(PNLIscrizioneStudenteLayout.createSequentialGroup()
                        .addComponent(LBLClasse, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(TXTClasse, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PNLIscrizioneStudenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BTNCreaStudente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BTNCancellaStudente, javax.swing.GroupLayout.DEFAULT_SIZE, 181, Short.MAX_VALUE)
                    .addComponent(BTNOrdinaGita, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BTNTornaIndietro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 456, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        PNLIscrizioneStudenteLayout.setVerticalGroup(
            PNLIscrizioneStudenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PNLIscrizioneStudenteLayout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PNLIscrizioneStudenteLayout.createSequentialGroup()
                .addGroup(PNLIscrizioneStudenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PNLIscrizioneStudenteLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(LBLTitoloStudenti)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PNLIscrizioneStudenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LBLNomeStudente)
                            .addComponent(TXTNomeStudente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(PNLIscrizioneStudenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LBLCognomeStudente)
                            .addComponent(TXTCognomeStudente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(PNLIscrizioneStudenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LBLCodiceStudente)
                            .addComponent(TXTCodiceStudente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(PNLIscrizioneStudenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TXTClasse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LBLClasse)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PNLIscrizioneStudenteLayout.createSequentialGroup()
                        .addComponent(BTNTornaIndietro, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(BTNOrdinaGita, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)))
                .addGroup(PNLIscrizioneStudenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PNLIscrizioneStudenteLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(BTNCancellaStudente, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(BTNCreaStudente, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PNLIscrizioneStudenteLayout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(LBLSelezionaGita)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addContainerGap())))
        );

        getContentPane().add(PNLIscrizioneStudente, new java.awt.GridBagConstraints());

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FRMStudenti().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTNCancellaStudente;
    private javax.swing.JButton BTNCreaStudente;
    private javax.swing.JButton BTNOrdinaGita;
    private javax.swing.JButton BTNTornaIndietro;
    private javax.swing.JLabel LBLClasse;
    private javax.swing.JLabel LBLCodiceStudente;
    private javax.swing.JLabel LBLCognomeStudente;
    private javax.swing.JLabel LBLNomeStudente;
    private javax.swing.JLabel LBLSelezionaGita;
    private javax.swing.JLabel LBLTitoloStudenti;
    private javax.swing.JList<String> LSTListaGite;
    private javax.swing.JPanel PNLIscrizioneStudente;
    private javax.swing.JTable TBLStudenti;
    private javax.swing.JTextField TXTClasse;
    private javax.swing.JTextField TXTCodiceStudente;
    private javax.swing.JTextField TXTCognomeStudente;
    private javax.swing.JTextField TXTNomeStudente;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
